version: '3.4'
services:
  lambda:
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      - FACTOR_TABLE=IOTFuse2018Factors
    depends_on:
      - dynamo
  dynamo:
    image: peopleperhour/dynamodb
